name: Deploy

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm
      - name: 安装依赖
        run: pnpm install
      - name: 打包
        run: pnpm docs:build
      - name: 部署
        uses: mynote/note-pages@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: docs/.vitepress/dist
